export type ChangeType = 'feature' | 'fix' | 'improvement'

export type Entry = {
  version: string
  date: string
  title: string
  description: string
  type: ChangeType
  tool: 'FAQ' | 'Platform'
}

export const changelog: Entry[] = [
  {
    version: 'v2.6',
    date: '20 May 2026',
    title: 'Keyword override per row',
    description: 'Expand any result row and a keyword bar shows the selected keyword with a pencil icon. Click to edit, type a new keyword, then click "Re-run with this keyword" to regenerate that row using your keyword instead of the GSC-selected one. Bypasses the keyword scoring pipeline entirely for that row.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.5',
    date: '20 May 2026',
    title: 'FAQ inline editing',
    description: 'Edit individual Q/A pairs directly in the result cards before downloading. Pencil icon per FAQ, click to turn question and answer into textareas, Save to confirm or X to discard. Edited indicator shown on saved items. Edits are reflected in the CSV download.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.4',
    date: '20 May 2026',
    title: 'Job status summary on dashboard',
    description: 'Completed jobs now show a row summary instead of a plain count: X ok in green and Y failed in red. Running and other statuses still show the plain completed/total count.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.3',
    date: '19 May 2026',
    title: 'Job duplication',
    description: 'Copy icon on each job in the dashboard. Duplicates the job settings and rows as a new draft job and navigates directly to it. No need to reconfigure settings for repeat runs.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.2',
    date: '19 May 2026',
    title: 'Re-run single row',
    description: 'Refresh icon on each result card in the cards view. Click to re-run just that URL through the full pipeline without rerunning the whole job. Spins while running, updates the result in place.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.1',
    date: '19 May 2026',
    title: 'Results table view',
    description: 'Toggle between Cards and Table view on the job results page. Table shows URL, keyword, source, scrape status, AI Overview, PAA count, FAQ count, and status for all rows at a glance. Click any row to open it in card view.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.0',
    date: '19 May 2026',
    title: 'Version bump to v2',
    description: 'Product is now public-facing with a real domain and landing page. Shifting from Streamlit parity work to genuine new features. v1.x = SaaS conversion. v2.x = product features.',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.31',
    date: '19 May 2026',
    title: 'Landing page',
    description: 'Built copypilot.app landing page. Hero with animated fade-in, tools suite showing FAQ Copy live and Meta Copy / Page Intro / Page Copy as coming soon, bottom CTA, footer. Matches dark theme of the FAQ tool.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.30',
    date: '19 May 2026',
    title: 'Public changelog at copypilot.app/changelog',
    description: 'Created copypilot-web project for the root domain. Changelog page at copypilot.app/changelog lists all versions as a static page matching the dark theme. Changelog moved from Notion to Craft and now also lives as a public static page.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.29',
    date: '19 May 2026',
    title: 'Live progress steps',
    description: 'Job processing now shows exactly what is happening at each step: scraping page, fetching GSC data, fetching DataForSEO keyword data, fetching AI Overview + PAA, generating FAQs. Batch mode shows Batch X/Y. Steps pulse in accent colour with percentage on the right.',
    type: 'feature',
    tool: 'FAQ',
  },
  {
    version: 'v1.28',
    date: '19 May 2026',
    title: 'Debug panel per result row',
    description: 'Each result row now has a collapsible debug panel matching the Streamlit app. Shows AI Overview YES/NO, attempts count, scrape status, PAA count, SERP types, and a full textarea with all data sent to AI: keyword, scraped page content, AI Overview raw, and PAA raw.',
    type: 'feature',
    tool: 'FAQ',
  },
  {
    version: 'v1.27',
    date: '16 May 2026',
    title: 'Final comprehensive audit',
    description: 'All 5 provider call functions verified identical to Streamlit. Integer key handling in generate_faq_batch confirmed correct. Auth key separation confirmed. 35 discrete checks all passing.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.26',
    date: '16 May 2026',
    title: 'Structural audit + URL validation in batch',
    description: 'URL validation added to batch mode (was only in single mode). import re moved to module level. Full endpoint and Supabase field mapping verified.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.25',
    date: '16 May 2026',
    title: 'Critical: runner_up key fix + rate limiting',
    description: 'Runner Up Keyword column was always blank due to wrong key (query vs keyword) when extracting from select_keyword result. Fixed in single and batch mode. Added rate limiting between batch AI calls. h1 "none" string now filtered. GSC debug info added to fallback keyword_source label.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.24',
    date: '16 May 2026',
    title: '46-point parity audit',
    description: 'URL validation for rows where URL does not start with http. faq_combined question filter added to batch mode. used_question_patterns now updated between batches so subsequent batches avoid repeating questions. _fingerprint_question moved to top-level import.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.23',
    date: '16 May 2026',
    title: 'Batch keyword selection parity',
    description: 'Batch keyword selection brought to full parity with single mode: GSC error handling, gsc+dfs/gsc-only labels, GSC-only fallback, runner_up tracking, has_dfs_volume check. Error result dict now includes all 16 CSV fields. faq_combined newline escaping fixed.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.22',
    date: '16 May 2026',
    title: 'Batch result assembly + paa_raw_text format',
    description: 'Batch result assembly was missing all diagnostic fields. GSC-only fallback when DFS returns zero volume. forbidden_phrases cleaned before passing to copy_gen. paa_raw_text now stores Q: .../A: ... format matching Streamlit.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.21',
    date: '16 May 2026',
    title: 'CSV column order + paa_raw_text',
    description: 'CSV column order fixed to match Streamlit exactly (schema before FAQ content/sources). paa_raw_text now includes answer snippets in Q/A format, not just questions.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.20',
    date: '16 May 2026',
    title: 'Parity: branded_terms_input + scrape_status detail',
    description: 'branded_terms_input was missing from JobSettings model. scrape_status now shows ok (N chars) and failed: error message matching Streamlit exactly.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.19',
    date: '16 May 2026',
    title: 'CSV columns: AI Overview Content + PAA Content',
    description: 'Two columns were missing from CSV export: AI Overview Content (ai_overview_raw_text) and PAA Content (paa_raw_text). Added and column order corrected to match Streamlit.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.18',
    date: '16 May 2026',
    title: 'JSX syntax fix',
    description: 'Fixed Vercel build failure caused by broken label tag structure when inserting the load_async_ai_overview toggle.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.17',
    date: '16 May 2026',
    title: 'Load async AI Overview toggle + branded terms',
    description: 'Added load_async_ai_overview toggle (doubles DFS cost, disable on large runs). Added branded terms to exclude textarea. Both were missing from the original SaaS build.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.16',
    date: '16 May 2026',
    title: 'Streamlit parity fixes',
    description: 'Scraper max_chars increased from 4000 to 10000. Full Brand Name field added for abbreviation expansion. Batch size default changed from 1 to 5. Keyword source labels now descriptive (gsc+dfs, gsc-only, fallback: ...). Forbidden phrases changed from comma-separated to textarea.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.15',
    date: '16 May 2026',
    title: 'Custom domain: faq.copypilot.app',
    description: 'Purchased copypilot.app on Vercel ($9.99/yr). FAQ tool connected to faq.copypilot.app. Permanent 308 redirect from faq-saas-frontend.vercel.app. CORS locked to new domain. Supabase redirect URLs updated.',
    type: 'feature',
    tool: 'Platform',
  },
  {
    version: 'v1.14',
    date: '15 May 2026',
    title: 'Backend crash fix',
    description: 'Fixed Railway crash caused by escaped quotes introduced by a bad str_replace in routers/faq.py. 54 instances of backslash-quote replaced. Python syntax was invalid, causing immediate crash on startup.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.13',
    date: '15 May 2026',
    title: 'Settings page redesign',
    description: 'About section redesigned with version badge, live backend health indicator with animated dot, GitHub repo links, and full stack tag list. GSC upload area improved with hover animation.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.12',
    date: '15 May 2026',
    title: 'TypeScript fix',
    description: 'Fixed Vercel build failure: Property faq_combined does not exist on type RowResult. Added all new diagnostic fields to the RowResult TypeScript type.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.11',
    date: '14 May 2026',
    title: 'Favicon',
    description: 'Added FAQ speech bubble favicon (two-tone mint green/grey). Applied to browser tab, sidebar logo, login and signup pages. All sizes generated.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.10',
    date: '14 May 2026',
    title: 'CSV output aligned to Streamlit',
    description: 'Previous CSV exported individual Q1/A1/Q2/A2 columns. Now exports 16 columns matching Streamlit: SEO Target Keyword, Keyword Source, Runner Up Keyword, Page Scrape Status, AI Overview Content, PAA Content, FAQ Content, FAQ Sources, FAQ Schema JSON-LD, FAQ Schema Script, FAQ Status.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.9',
    date: '14 May 2026',
    title: 'Inline job rename',
    description: 'Hover a job name on the dashboard to reveal a pencil icon. Click to edit in place, Enter to save, Escape to cancel.',
    type: 'feature',
    tool: 'FAQ',
  },
  {
    version: 'v1.8',
    date: '14 May 2026',
    title: 'Batch size slider',
    description: 'Replaced batch mode on/off toggle with a slider from 1 to 15. Live explanation text updates as you drag. 1 = per-page mode (default 5). Backend groups pages into batches of batch_size per AI call.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.7',
    date: '14 May 2026',
    title: 'Resizable columns',
    description: 'Replaced grid-based table with pixel-width layout. Drag handles on URL, Keyword, Type, H1 column headers. Minimum column width 80px. Row area scrolls horizontally.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.6',
    date: '14 May 2026',
    title: 'Row management',
    description: 'Added multi-select checkboxes to manual row input. Select all / deselect all via header checkbox. Delete selected rows. Clear all button. Live URL count display.',
    type: 'feature',
    tool: 'FAQ',
  },
  {
    version: 'v1.5',
    date: '14 May 2026',
    title: 'Input UX improvements',
    description: 'Fixed page type case sensitivity. Flexible CSV column name matching (type, Type, page_type, Page Type all accepted). Smart paste parser auto-detects 2, 3, or 4 column formats.',
    type: 'improvement',
    tool: 'FAQ',
  },
  {
    version: 'v1.4',
    date: '14 May 2026',
    title: 'AI model selection',
    description: 'Added per-provider model dropdown. Model resets to provider default when switching. Claude: Sonnet 4.6/4.5/Haiku. OpenAI: GPT-5.5/5.4. Gemini: 2.0 Flash. Mistral: Small/Large. Groq: Llama 3 70B/8B/3.3 70B.',
    type: 'feature',
    tool: 'FAQ',
  },
  {
    version: 'v1.3',
    date: '14 May 2026',
    title: 'Git author fix',
    description: 'Rewrote commit history on both repos to use the noreply GitHub email. Prevented Vercel deployment blocks caused by unrecognised commit author.',
    type: 'fix',
    tool: 'Platform',
  },
  {
    version: 'v1.2',
    date: '14 May 2026',
    title: 'Auth callback + email branding',
    description: 'Added /auth/callback route to handle Supabase email confirmation. Set Supabase Site URL and Redirect URLs to Vercel domain. Added branded HTML email template for signup confirmation.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.1',
    date: '14 May 2026',
    title: 'Supabase key fix',
    description: 'Fixed SupabaseException: Invalid API key. Switched from new sb_publishable_ key format to legacy JWT keys. Bumped supabase-py from 2.9.0 to 2.15.0.',
    type: 'fix',
    tool: 'FAQ',
  },
  {
    version: 'v1.0',
    date: '13 May 2026',
    title: 'Initial build',
    description: 'Full stack built from scratch as a standalone SaaS product, converted from the internal Streamlit app. FastAPI backend on Railway, Next.js frontend on Vercel, Supabase auth and DB. Auth flow, dashboard, new job page with manual/paste/CSV input, results page with CSV download, settings page.',
    type: 'feature',
    tool: 'FAQ',
  },
]
