export type ChangeType = 'feature' | 'fix' | 'improvement'

export type Entry = {
  version: string
  date: string
  title: string
  description: string
  type: ChangeType
  tool: 'FAQ' | 'Intro' | 'Indexer' | 'Platform'
}

export const changelog: Entry[] = [
  {
    version: 'v3.1 / intro v1.3',
    date: '28 May 2026',
    title: 'Keyword scoring fixes across all tools',
    description: 'CTR now capped at 15% to prevent outlier brand queries from dominating keyword selection. Restricted industry mode added to both FAQ and Intro new job forms — for industries where DFS suppresses volume data (CBD, guns, dispensaries, adult), scores keywords on GSC engagement signals only (impressions, clicks, CTR, position) with no volume or difficulty weighting. Zero-volume keywords with real GSC impressions are no longer dropped silently — they enter the pool with a 0.1 penalty in standard mode and compete equally in restricted mode. Position score formula unified to 1/(1+max(0,pos-20)*0.1) across all tools.',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.1 / intro v1.2',
    date: '26 May 2026',
    title: 'Multi-brand profiles',
    description: 'Replaced the single brand profile with a full brand profiles manager in Settings. Create one profile per client or brand, each with its own voice, tone, audience, USPs, key messages, products, competitors, words to avoid, and example copy. Select which profile to apply when creating a job via a dropdown. The selected profile is fetched at processing time and injected into every prompt. Profiles are shared across FAQ and Page Intro tools from the same Supabase instance.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.0',
    date: '22 May 2026',
    title: 'Job templates',
    description: 'Save any job configuration as a named template. Templates appear at the top of the new job form. Click to load all settings instantly — provider, business type, brand name, FAQ count, forbidden phrases, batch size, GSC and scrape toggles. Delete templates on hover. Scoped per tool and per user.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.9',
    date: '22 May 2026',
    title: 'Brand profile (single)',
    description: 'Full brand profile card in Settings. Nine fields: brand name, tone, brand voice, target audience, USPs, key messages, products/services, competitors, words to avoid, and example copy. Stored once, injected into every prompt automatically for both single and batch mode. Brand name pre-fills on every new job. Superseded by multi-brand profiles in v3.1.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.8',
    date: '21 May 2026',
    title: 'Save site URL + empty state + form validation',
    description: 'GSC site URL now saved with credentials in Settings and pre-filled on every new job. Empty dashboard now shows an onboarding message with a link to Settings. Submitting a job with GSC enabled but no site URL now shows a clear error instead of failing silently.',
    type: 'improvement' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.7',
    date: '20 May 2026',
    title: 'Saved API credentials',
    description: 'New Credentials card in Settings. Save your AI provider key, DataForSEO login/password, and Jina API key once. Every new job pre-fills all fields automatically. Keys are stored server-side and never returned to the browser.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.6',
    date: '20 May 2026',
    title: 'Keyword override per row',
    description: 'Expand any result row and a keyword bar shows the selected keyword with a pencil icon. Click to edit, type a new keyword, then click "Re-run with this keyword" to regenerate that row using your keyword instead of the GSC-selected one. Bypasses the keyword scoring pipeline entirely for that row.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.5',
    date: '20 May 2026',
    title: 'FAQ inline editing',
    description: 'Edit individual Q/A pairs directly in the result cards before downloading. Pencil icon per FAQ, click to turn question and answer into textareas, Save to confirm or X to discard. Edits are reflected in the CSV download.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.4',
    date: '20 May 2026',
    title: 'Job status summary on dashboard',
    description: 'Completed jobs now show a row summary: X ok in green and Y failed in red.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.3',
    date: '19 May 2026',
    title: 'Job duplication',
    description: 'Copy icon on each job in the dashboard. Duplicates the job settings and rows as a new draft and navigates directly to it.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.2',
    date: '19 May 2026',
    title: 'Re-run single row',
    description: 'Refresh icon on each result card. Click to re-run just that URL through the full pipeline without rerunning the whole job.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.1',
    date: '19 May 2026',
    title: 'Results table view',
    description: 'Toggle between Cards and Table view on the job results page. Table shows URL, keyword, source, scrape status, AI Overview, PAA count, FAQ count, and status for all rows at a glance.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.0',
    date: '19 May 2026',
    title: 'Version bump to v2',
    description: 'Product is now public-facing with a real domain and landing page. v1.x = SaaS conversion from Streamlit. v2.x = new product features. v3.x = platform-wide features (templates, brand profiles).',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'intro v1.1',
    date: '25 May 2026',
    title: 'Page Intro tool launched',
    description: 'Page Intro Production tool live at intro.copypilot.app. Three-source keyword pool (GSC + DFS ranked keywords + manual seeds). Six page templates: Category, Product, Service/Landing Page, Location, Blog/Editorial, Brand/About. H1 fallback when no keyword data found. used_primaries deduplication across the job run. Settings page with credentials, brand profile, and about card.',
    type: 'feature' as const,
    tool: 'Intro' as const,
  },
  {
    version: 'indexer v1.1',
    date: '28 May 2026',
    title: 'Re-request selected URLs + about card',
    description: 'Checkbox selection on results page. Select any combination of URLs and click "Re-request N URLs" to create a new job with just those. Select all via header checkbox. Settings about card now matches FAQ and Intro style with backend health indicator, repo links, and stack tags.',
    type: 'feature' as const,
    tool: 'Indexer' as const,
  },
  {
    version: 'indexer v1.0',
    date: '24 May 2026',
    title: 'Google Indexer launched',
    description: 'Indexer tool live at indexer.copypilot.app. Submit URLs for Google indexing via the Indexing API. Paste URLs, upload CSV, or submit via sitemap. Daily 200-URL quota tracking. Results table with per-URL status (submitted, failed, queued, quota exceeded). GSC service account upload in Settings.',
    type: 'feature' as const,
    tool: 'Indexer' as const,
  },
  {
    version: 'v1.31',
    date: '19 May 2026',
    title: 'Landing page',
    description: 'Built copypilot.app landing page. Hero with animated fade-in, tools suite showing FAQ Copy live and Meta Copy / Page Intro / Page Copy as coming soon, bottom CTA, footer.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.30',
    date: '19 May 2026',
    title: 'Public changelog',
    description: 'Changelog page at copypilot.app/changelog. Lists all versions as a static page matching the dark theme.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.0',
    date: '13 May 2026',
    title: 'FAQ tool initial build',
    description: 'Full stack built from scratch as a standalone SaaS product, converted from the internal Streamlit app. FastAPI backend on Railway, Next.js frontend on Vercel, Supabase auth and DB. Auth flow, dashboard, new job page with manual/paste/CSV input, results page with CSV download, settings page.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
]
