export type ChangeType = 'feature' | 'fix' | 'improvement'

export type Entry = {
  version: string
  date: string
  title: string
  description: string
  type: ChangeType
  tool: 'FAQ' | 'Intro' | 'Indexer' | 'Platform'
}

export const changelog: Entry[] = [
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Light mode default + theme toggle',
    description: 'All four apps now default to a warm light theme (#FAF8F5 background, white surfaces, warm dark text) modelled on AirOps and modern SaaS design standards. A light/dark toggle sits at the bottom of the sidebar in each app — preference is saved per user in localStorage and persists across sessions. The switch is instant with a 0.2s ease transition. Dark mode remains fully supported for team members who prefer it.',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Live job log panel',
    description: 'While a job is running, the job page now splits into two columns. The left shows the progress bar and current step. The right shows a live scrolling log — every step the backend processes is appended with a +Xs elapsed time marker in monospace font. After the job completes, the log collapses to a toggleable "Show/Hide run log (N steps)" section above the results, so you can review what happened per row. Covers both FAQ and Page Intro SaaS tools.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Detailed step outcome logging',
    description: 'Each pipeline step now logs its result, not just its intent. The log shows: scrape result (ok with char count, or failed with reason), GSC query count found, keyword selected with source label and volume, SERP outcome (AIO present/absent, PAA question count, interrogative fallback triggered), and FAQs/intro generated count or error. This makes it easy to spot issues — no GSC data, no keyword selected, empty SERP — before the AI call is made, so you can stop the job before burning API credits on bad data.',
    type: 'improvement' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Stop job button',
    description: 'A red Stop job button now appears in the job header while any job is running or cancelling. Clicking it sets the job status to cancelling — the backend checks for this flag after each row (single mode) or after each batch (batch mode) and stops gracefully, saving whatever results were already produced. The partial CSV is still downloadable. Covers both FAQ and Page Intro SaaS tools.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Multi-row rerun with checkboxes',
    description: 'After a job completes, each result card now has a checkbox. Select any combination of rows and click Re-run N rows to reprocess them in place without starting a new job. A Select all failed button appears automatically when any rows have errors. Select all / deselect all checkbox in the toolbar handles the whole set at once. Covers both FAQ and Page Intro SaaS tools.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.2',
    date: '30 May 2026',
    title: 'Interrogative fallback for empty SERP results',
    description: 'When a keyword returns no AIO and no PAA data, the FAQ tool now automatically tries interrogative prefixes in order — "what [keyword]", then "how [keyword]", then "why [keyword]" — and uses the first one that returns PAA or AIO data as the generation signal. If none return data, generation continues with page context only. Applied to both FAQ SaaS and FAQ Streamlit.',
    type: 'improvement' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v3.2',
    date: '30 May 2026',
    title: 'Batch cap and timeout fixes',
    description: 'Batch mode now hard-caps at 20 pages per AI call regardless of the slider setting — larger batches were causing silent timeouts and empty results. A 180-second SIGALRM timeout per batch ensures a hung AI call fails gracefully and the job continues rather than freezing indefinitely. AIO retry attempts reduced from 5 to 3, retry sleep from 3s to 1.5s — eliminating up to 12 seconds of wasted sleep per URL. Applied to both FAQ SaaS and FAQ Streamlit.',
    type: 'fix' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v3.2',
    date: '30 May 2026',
    title: 'max_tokens increased to 16,384 for Claude and OpenAI',
    description: 'Single-row FAQ generation was using a 2048 token limit, which was insufficient for 5+ detailed technical FAQ pairs. The response was being truncated mid-JSON, producing empty results silently. Claude and OpenAI are now set to 16,384 tokens (enough for 50 FAQs comfortably). Gemini, Mistral, and Groq remain at 4,096 due to free-tier limits. Partial JSON recovery also added — if a response is still truncated, all complete FAQ objects before the cutoff are salvaged.',
    type: 'fix' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Brand & Copy Guidelines textarea (Streamlit apps)',
    description: 'Both the FAQ and Page Intro Streamlit apps now have a Brand & Copy Guidelines text area in the sidebar. Paste any free-form brand context — voice, tone, audience, USPs, words to avoid, competitor notes, or a full copy brief — and it is injected into every prompt for that run. No rigid fields, no saving required. Supports any format.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.2 / intro v1.4',
    date: '30 May 2026',
    title: 'Rerun credentials fix',
    description: 'Single-row and multi-row reruns were failing with API key errors and GSC 403s because credentials are deliberately excluded from stored job settings for security. Both rerun paths now fetch the API key, DFS password, and GSC service account from user_settings at rerun time, filtered by the authenticated user ID. This fixes all rerun failures caused by missing credentials.',
    type: 'fix' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.1 / intro v1.3',
    date: '28 May 2026',
    title: 'Keyword scoring fixes across all tools',
    description: 'CTR now capped at 15% to prevent outlier brand queries from dominating keyword selection. Restricted industry mode added to both FAQ and Intro new job forms — for industries where DFS suppresses volume data (CBD, guns, dispensaries, adult), scores keywords on GSC engagement signals only (impressions, clicks, CTR, position) with no volume or difficulty weighting. Zero-volume keywords with real GSC impressions are no longer dropped silently — they enter the pool with a 0.1 penalty in standard mode and compete equally in restricted mode. Position score formula unified to 1/(1+max(0,pos-20)*0.1) across all tools.',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.1 / intro v1.2',
    date: '26 May 2026',
    title: 'Multi-brand profiles',
    description: 'Replaced the single brand profile with a full brand profiles manager in Settings. Create one profile per client or brand, each with its own voice, tone, audience, USPs, key messages, products, competitors, words to avoid, and example copy. Select which profile to apply when creating a job via a dropdown. The selected profile is fetched at processing time and injected into every prompt. Profiles are shared across FAQ and Page Intro tools from the same Supabase instance.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v3.0',
    date: '22 May 2026',
    title: 'Job templates',
    description: 'Save any job configuration as a named template. Templates appear at the top of the new job form. Click to load all settings instantly — provider, business type, brand name, FAQ count, forbidden phrases, batch size, GSC and scrape toggles. Delete templates on hover. Scoped per tool and per user.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.9',
    date: '22 May 2026',
    title: 'Brand profile (single)',
    description: 'Full brand profile card in Settings. Nine fields: brand name, tone, brand voice, target audience, USPs, key messages, products/services, competitors, words to avoid, and example copy. Stored once, injected into every prompt automatically for both single and batch mode. Brand name pre-fills on every new job. Superseded by multi-brand profiles in v3.1.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.8',
    date: '21 May 2026',
    title: 'Save site URL + empty state + form validation',
    description: 'GSC site URL now saved with credentials in Settings and pre-filled on every new job. Empty dashboard now shows an onboarding message with a link to Settings. Submitting a job with GSC enabled but no site URL now shows a clear error instead of failing silently.',
    type: 'improvement' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.7',
    date: '20 May 2026',
    title: 'Saved API credentials',
    description: 'New Credentials card in Settings. Save your AI provider key, DataForSEO login/password, and Jina API key once. Every new job pre-fills all fields automatically. Keys are stored server-side and never returned to the browser.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.6',
    date: '20 May 2026',
    title: 'Keyword override per row',
    description: 'Expand any result row and a keyword bar shows the selected keyword with a pencil icon. Click to edit, type a new keyword, then click "Re-run with this keyword" to regenerate that row using your keyword instead of the GSC-selected one. Bypasses the keyword scoring pipeline entirely for that row.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.5',
    date: '20 May 2026',
    title: 'FAQ inline editing',
    description: 'Edit individual Q/A pairs directly in the result cards before downloading. Pencil icon per FAQ, click to turn question and answer into textareas, Save to confirm or X to discard. Edits are reflected in the CSV download.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.4',
    date: '20 May 2026',
    title: 'Job status summary on dashboard',
    description: 'Completed jobs now show a row summary: X ok in green and Y failed in red.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.3',
    date: '19 May 2026',
    title: 'Job duplication',
    description: 'Copy icon on each job in the dashboard. Duplicates the job settings and rows as a new draft and navigates directly to it.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.2',
    date: '19 May 2026',
    title: 'Re-run single row',
    description: 'Refresh icon on each result card. Click to re-run just that URL through the full pipeline without rerunning the whole job.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.1',
    date: '19 May 2026',
    title: 'Results table view',
    description: 'Toggle between Cards and Table view on the job results page. Table shows URL, keyword, source, scrape status, AI Overview, PAA count, FAQ count, and status for all rows at a glance.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
  {
    version: 'v2.0',
    date: '19 May 2026',
    title: 'Version bump to v2',
    description: 'Product is now public-facing with a real domain and landing page. v1.x = SaaS conversion from Streamlit. v2.x = new product features. v3.x = platform-wide features (templates, brand profiles).',
    type: 'improvement' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'intro v1.1',
    date: '25 May 2026',
    title: 'Page Intro tool launched',
    description: 'Page Intro Production tool live at intro.copypilot.app. Three-source keyword pool (GSC + DFS ranked keywords + manual seeds). Six page templates: Category, Product, Service/Landing Page, Location, Blog/Editorial, Brand/About. H1 fallback when no keyword data found. used_primaries deduplication across the job run. Settings page with credentials, brand profile, and about card.',
    type: 'feature' as const,
    tool: 'Intro' as const,
  },
  {
    version: 'indexer v1.1',
    date: '28 May 2026',
    title: 'Re-request selected URLs + about card',
    description: 'Checkbox selection on results page. Select any combination of URLs and click "Re-request N URLs" to create a new job with just those. Select all via header checkbox. Settings about card now matches FAQ and Intro style with backend health indicator, repo links, and stack tags.',
    type: 'feature' as const,
    tool: 'Indexer' as const,
  },
  {
    version: 'indexer v1.0',
    date: '24 May 2026',
    title: 'Google Indexer launched',
    description: 'Indexer tool live at indexer.copypilot.app. Submit URLs for Google indexing via the Indexing API. Paste URLs, upload CSV, or submit via sitemap. Daily 200-URL quota tracking. Results table with per-URL status (submitted, failed, queued, quota exceeded). GSC service account upload in Settings.',
    type: 'feature' as const,
    tool: 'Indexer' as const,
  },
  {
    version: 'v1.31',
    date: '19 May 2026',
    title: 'Landing page',
    description: 'Built copypilot.app landing page. Hero with animated fade-in, tools suite showing FAQ Copy live and Meta Copy / Page Intro / Page Copy as coming soon, bottom CTA, footer.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.30',
    date: '19 May 2026',
    title: 'Public changelog',
    description: 'Changelog page at copypilot.app/changelog. Lists all versions as a static page matching the dark theme.',
    type: 'feature' as const,
    tool: 'Platform' as const,
  },
  {
    version: 'v1.0',
    date: '13 May 2026',
    title: 'FAQ tool initial build',
    description: 'Full stack built from scratch as a standalone SaaS product, converted from the internal Streamlit app. FastAPI backend on Railway, Next.js frontend on Vercel, Supabase auth and DB. Auth flow, dashboard, new job page with manual/paste/CSV input, results page with CSV download, settings page.',
    type: 'feature' as const,
    tool: 'FAQ' as const,
  },
]
